### ISSUE TITLE
Order of Assessments

### ISSUE THREAD

**Issue by WillKang01** [UBC-LFS/Canvas-Flexible-Assessment#23]
Django apparently renders Formsets in the [order they are created](https://docs.djangoproject.com/en/4.2/topics/forms/formsets/#:~:text=Iterating%20over%20a%20formset%20will%20render%20the%20forms%20in%20the%20order%20they%20were%20created.%20You%20can%20change%20this%20order%20by%20providing%20an%20alternate%20implementation%20for%20the%20__iter__()%20method.), but this does not appear to be consistent on the server. Sometimes the order changes and appears different for different users.

Look into form set ordering: https://docs.djangoproject.com/en/4.2/topics/forms/formsets/#dealing-with-ordering-and-deletion-of-forms

**Comment by wflyerthariani** [comment]
Ordering is now done by additional field in database for flex assessments, allows instructor to order forms and changes are saved for instructor and student
